name: expect_error_plus
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  change_case: ^1.0.1
  expect_error:
    git: https://github.com/mrgnhnt96/expect_error

dev_dependencies:
  very_good_analysis: ^2.4.0
